version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: alxpropertydb
      POSTGRES_USER: alxuser
      POSTGRES_PASSWORD: alxpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  pgdata:
